### ISSUE TITLE
js端如何定义NativeCall

### ISSUE THREAD

**Issue by yangguansen** [xd-tayde/blog#1]
博主你好，我看到你文章中说明了native端如何去调用js的NativeCall，但是在js中如何去声明这个NativeCall呢？

**Comment by xd-tayde** [comment]
bridge中的api是H5/Native都可以调用的，而nativeCall就是封装在bridge.js中，具体的代码实现，会在接下来第二篇文章中介绍哈。~

**Comment by yangguansen** [comment]
博主第二篇求更
