### ISSUE TITLE
關於 blog 發佈到其他平台的方式

### ISSUE THREAD

**Issue by fangchih** [xd-tayde/blog#3]
首先謝謝分享。

看您並不是用 github page 發佈博文，而是發佈到其他平台上，請問是不是有自動化的方式呢？

**Comment by xd-tayde** [comment]
哈哈。没有呢。。我是手动去发布的。~😂

**Comment by fangchih** [comment]
哇，真是辛苦你了。 會建議使用 blog generator 生成 github page 嗎？

**Comment by xd-tayde** [comment]
不错呀。以前我也有做过。。可以搭个个人博客。~

**Comment by zlccns** [comment]
数学部分我看的很仔细，但最终看的一脸懵逼...

**Comment by xd-tayde** [comment]
哈哈~加油。。其实还是比较好理解的。
